// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Kentico.Kontent.Statiq.Lumen.Models
{
    public partial class Article
    {
        public const string Codename = "article";
        public const string CategoryCodename = "category";
        public const string ContentCodename = "content";
        public const string DateCodename = "date";
        public const string DescriptionCodename = "description";
        public const string SlugCodename = "slug";
        public const string SocialSharingMetadataDescriptionCodename = "social_sharing_metadata__description";
        public const string SocialSharingMetadataKeywordsCodename = "social_sharing_metadata__keywords";
        public const string SocialSharingMetadataOgDescriptionCodename = "social_sharing_metadata__og_description";
        public const string SocialSharingMetadataOgImageCodename = "social_sharing_metadata__og_image";
        public const string SocialSharingMetadataOgTitleCodename = "social_sharing_metadata__og_title";
        public const string SocialSharingMetadataTeaserImageCodename = "social_sharing_metadata__teaser_image";
        public const string SocialSharingMetadataTwitterCardCodename = "social_sharing_metadata__twitter_card";
        public const string SocialSharingMetadataTwitterCreatorCodename = "social_sharing_metadata__twitter_creator";
        public const string SocialSharingMetadataTwitterImageCodename = "social_sharing_metadata__twitter_image";
        public const string SocialSharingMetadataTwitterSiteCodename = "social_sharing_metadata__twitter_site";
        public const string TagsCodename = "tags";
        public const string TitleCodename = "title";

        public IEnumerable<object> Category { get; set; }
        public string Content { get; set; }
        public DateTime? Date { get; set; }
        public string Description { get; set; }
        public string Slug { get; set; }
        public string SocialSharingMetadataDescription { get; set; }
        public string SocialSharingMetadataKeywords { get; set; }
        public string SocialSharingMetadataOgDescription { get; set; }
        public IEnumerable<IAsset> SocialSharingMetadataOgImage { get; set; }
        public string SocialSharingMetadataOgTitle { get; set; }
        public IEnumerable<IAsset> SocialSharingMetadataTeaserImage { get; set; }
        public IEnumerable<IMultipleChoiceOption> SocialSharingMetadataTwitterCard { get; set; }
        public string SocialSharingMetadataTwitterCreator { get; set; }
        public IEnumerable<IAsset> SocialSharingMetadataTwitterImage { get; set; }
        public string SocialSharingMetadataTwitterSite { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<object> Tags { get; set; }
        public string Title { get; set; }
    }
}