// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Kentico.Kontent.Statiq.Lumen.Models
{
    public partial class MenuItem
    {
        public const string Codename = "menu_item";
        public const string ContentCodename = "content";
        public const string LabelCodename = "label";
        public const string SlugCodename = "slug";

        public IEnumerable<object> Content { get; set; }
        public string Label { get; set; }
        public string Slug { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}